import {useEffect,useMemo,useState} from "react";
import "./App.css";
import AENOVALogo from "./assets/AENOVA-logo.png";
import HeroStudent from "./assets/HeroStudent.png";

const API="https://aenova.onrender.com";
const initial={full_name:"",email:"",college:"",course:"",study_year:"",skills:"",interests:"",career_goal:"",location:"",preferred_scope:"Anywhere in India",preferred_cities:"",notification_enabled:true,notification_categories:"Hackathon,Internship,Competition,Workshop",notification_frequency:"daily"};

function match(o,p){const s=JSON.stringify(o).toLowerCase(),t=`${p.skills} ${p.interests} ${p.course} ${p.career_goal} ${p.location}`.toLowerCase();let n=0; t.split(/[,; ]+/).filter(x=>x.length>2).forEach(x=>{if(s.includes(x))n+=8});return Math.min(99,n)}
function Card({o,p,fb,setFb}){const k=o.id||o.source_id||o.official_url||o.url||o.title,m=match(o,p);return <div className="card"><div className="cardtop"><b>{o.category||"Opportunity"}</b><small>LIVE · {o.source||"PUBLIC"}</small></div><h3>{o.title}</h3><p>{o.description||"See the official listing for complete details."}</p><div className="chips"><span>🎯 {o.field||"All Fields / General"}</span><span>🏢 {o.organization||"Organization not available"}</span><span>📍 {o.location||"See official listing"}</span><span>💻 {o.mode||"See official listing"}</span></div><div className="meta">{o.deadline&&<span>⏰ {o.deadline}</span>}{o.event_date&&<span>📅 {o.event_date}</span>}{o.eligibility&&<span>✓ {o.eligibility}</span>}</div>{p.full_name&&m>0&&<div className="match"><b>{m}% match</b><span>Based on your profile</span></div>}<div className="actions"><button onClick={()=>setFb({...fb,[k]:"like"})}>👍</button><button onClick={()=>setFb({...fb,[k]:"dislike"})}>👎</button>{(o.official_url||o.url)&&<a href={o.official_url||o.url} target="_blank" rel="noreferrer">Official Listing →</a>}</div></div>}

export default function App(){
 const[p,setP]=useState(()=>JSON.parse(localStorage.getItem("aenova_profile")||"null")||initial),[ops,setOps]=useState([]),[loading,setLoading]=useState(true),[view,setView]=useState("recommended"),[cat,setCat]=useState("All"),[field,setField]=useState("All"),[loc,setLoc]=useState("All"),[modal,setModal]=useState(false),[step,setStep]=useState(0),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[fb,setFb]=useState(()=>JSON.parse(localStorage.getItem("aenova_feedback")||"{}")),[chat,setChat]=useState([{r:"a",t:"Hi! 👋 I’m ANEBESTRA. Tell me what you want to discover, learn, or build."}]),[text,setText]=useState(""),[sending,setSending]=useState(false);
 const sid=useMemo(()=>localStorage.getItem("aenova_session")||(()=>{const x=crypto.randomUUID();localStorage.setItem("aenova_session",x);return x})(),[]);
 const load=()=>{setLoading(true);fetch(API+"/api/opportunities").then(r=>r.json()).then(d=>setOps(Array.isArray(d)?d:(d.opportunities||[]))).catch(()=>setOps([])).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[]);useEffect(()=>localStorage.setItem("aenova_profile",JSON.stringify(p)),[p]);useEffect(()=>localStorage.setItem("aenova_feedback",JSON.stringify(fb)),[fb]);
 const fields=["All",...new Set(ops.map(x=>x.field).filter(Boolean))];
 let list=ops.filter(o=>cat==="All"||(o.category||"").toLowerCase()===cat.toLowerCase()).filter(o=>field==="All"||o.field===field).filter(o=>loc==="All"||`${o.location} ${o.mode}`.toLowerCase().includes(loc.toLowerCase()));
 if(view==="recommended"&&p.full_name)list=[...list].map(o=>({...o,__m:match(o,p)})).sort((a,b)=>b.__m-a.__m);
 const u=(k,v)=>setP(x=>({...x,[k]:v}));
 async function save(){if(!p.full_name||!p.email){setMsg("Name and email are required.");return}setSaving(true);try{const r=await fetch(API+"/api/profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}),d=await r.json();if(d.success===false)throw Error(d.message);setModal(false);setMsg("Profile saved — your feed is personalized.");document.getElementById("feed")?.scrollIntoView({behavior:"smooth"})}catch(e){setMsg(e.message||"Could not save profile")}finally{setSaving(false)}}
 async function send(){if(!text.trim()||sending)return;const q=text.trim();setText("");setChat(x=>[...x,{r:"u",t:q}]);setSending(true);try{const r=await fetch(API+"/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q,session_id:sid,profile:p})}),d=await r.json();setChat(x=>[...x,{r:"a",t:d.reply||"Please try again."}])}catch{setChat(x=>[...x,{r:"a",t:"I couldn't connect right now. Please try again."}])}finally{setSending(false)}}
 const stepContent=[
 <><h3>👋 About you</h3><label>Full name<input value={p.full_name} onChange={e=>u("full_name",e.target.value)} placeholder="Your name"/></label><label>Email<input value={p.email} onChange={e=>u("email",e.target.value)} placeholder="you@example.com"/></label></>,
 <><h3>🎓 Education</h3><label>College / University<input value={p.college} onChange={e=>u("college",e.target.value)}/></label><label>Course / Degree<input value={p.course} onChange={e=>u("course",e.target.value)} placeholder="B.Tech, B.Com, MBBS, LLB…"/></label><label>Study year<select value={p.study_year} onChange={e=>u("study_year",e.target.value)}><option value="">Select</option><option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>4th Year</option><option>Final Year</option><option>Postgraduate</option></select></label></>,
 <><h3>🧠 Skills & interests</h3><label>Skills<input value={p.skills} onChange={e=>u("skills",e.target.value)} placeholder="Python, design, finance, writing…"/></label><label>Interests<input value={p.interests} onChange={e=>u("interests",e.target.value)} placeholder="AI, law, medicine, entrepreneurship…"/></label><label>Career goal<textarea value={p.career_goal} onChange={e=>u("career_goal",e.target.value)}/></label></>,
 <><h3>📍 Location</h3><label>Current location<input value={p.location} onChange={e=>u("location",e.target.value)} placeholder="City / State"/></label><label>Preferred scope<select value={p.preferred_scope} onChange={e=>u("preferred_scope",e.target.value)}><option>Anywhere in India</option><option>Tamil Nadu</option><option>My city only</option><option>Online</option></select></label><label>Preferred cities<input value={p.preferred_cities} onChange={e=>u("preferred_cities",e.target.value)} placeholder="Chennai, Coimbatore, Madurai…"/></label></>,
 <><h3>✉ Email alerts</h3><label className="check"><input type="checkbox" checked={p.notification_enabled} onChange={e=>u("notification_enabled",e.target.checked)}/> Send relevant opportunity alerts</label><label>Categories<input value={p.notification_categories} onChange={e=>u("notification_categories",e.target.value)}/></label><label>Frequency<select value={p.notification_frequency} onChange={e=>u("notification_frequency",e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label></>
 ];
 return <div><nav><a href="#home"><img src={AENOVALogo}/></a><div><a href="#how">How it works</a><a href="#feed">Recommendations</a><a href="#explore">Explore</a><a href="#assistant">ANEBESTRA</a><button onClick={()=>setModal(true)}>Get Started →</button></div></nav>
 <section className="hero" id="home"><div><small>✦ AI-POWERED OPPORTUNITY DISCOVERY</small><h1>Discover opportunities.<br/><em>Build your future.</em></h1><p>AENOVA understands your education, skills, interests, career goals and location to create a personalized student experience.</p><button className="primary" onClick={()=>setModal(true)}>Get Started →</button><a className="outline" href="#feed">Explore opportunities</a></div><div className="heroimg"><i></i><img src={HeroStudent}/></div></section>
 <section><div className="heading"><small>✦ THE AENOVA LOOP</small><h2>One profile. <em>Three ways forward.</em></h2><p>Everything connects into one personalized experience.</p></div><div className="loop"><button onClick={()=>setModal(true)}>👤<b>Student Profile</b><span>Tell AENOVA who you are.</span></button><button onClick={()=>{setView("recommended");document.getElementById("feed").scrollIntoView()}}>🎯<b>Recommended</b><span>Matches based on your profile.</span></button><button onClick={()=>{setView("explore");document.getElementById("feed").scrollIntoView()}}>🔎<b>Explore</b><span>Browse across fields and locations.</span></button><button onClick={()=>document.getElementById("assistant").scrollIntoView()}>🤖<b>ANEBESTRA</b><span>Ask, plan, learn and decide.</span></button></div></section>
 <section className="dark" id="how"><div className="heading"><small>✦ HOW AENOVA WORKS</small><h2>From profile to <em>opportunity.</em></h2></div><div className="pipeline"><span>01<br/>👤<b>Student Profile</b><small>Education · Skills · Goals · Location</small></span><b>→</b><span>02<br/>🧠<b>AENOVA understands</b><small>Relevant profile signals</small></span><b>→</b><span>03<br/>🎯<b>Recommendation Engine</b><small>Ranks relevant listings</small></span><b>→</b><span>04<br/>🚀<b>Personalized Feed</b><small>Discover · Explore · Act</small></span></div></section>
 <section><div className="heading"><small>✦ OPPORTUNITY ENGINE</small><h2>From sources to <em>student discovery.</em></h2></div><div className="sourcegrid"><div><b>Unstop</b><span>Internships · Hackathons · Competitions · Jobs · Events</span></div><div><b>AICTE</b><span>Internships · Government opportunities</span></div><div><b>NSP</b><span>Scholarships · Schemes</span></div></div><div className="processing"><span>VALIDATION</span><span>DEDUPLICATION</span><span>FIELD CLASSIFICATION</span><span>LOCATION CLASSIFICATION</span></div><div className="database">☁ SUPABASE OPPORTUNITY DATABASE</div><div className="outputs"><span>🎯 Recommended</span><span>🔎 Explore</span><span>🤖 ANEBESTRA</span><span>✉ Email Alerts</span></div></section>
 <section id="feed" className="feed"><div className="heading"><small>✦ PERSONALIZED FEED</small><h2>{p.full_name?`Opportunities for ${p.full_name}.`:"Your opportunities, personalized."}</h2><p>{p.full_name?"Ranked using your profile.":"Complete your profile to personalize this feed."}</p></div>{!p.full_name&&<button className="banner" onClick={()=>setModal(true)}>👤 Complete your student profile <b>Get personalized matches →</b></button>}<div className="tabs"><button className={view==="recommended"?"on":""} onClick={()=>setView("recommended")}>🎯 Recommended</button><button className={view==="explore"?"on":""} onClick={()=>setView("explore")}>🔎 Explore</button></div><div className="filters"><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option><option>Hackathon</option><option>Internship</option><option>Competition</option><option>Workshop</option></select><select value={field} onChange={e=>setField(e.target.value)}>{fields.map(x=><option key={x}>{x}</option>)}</select><select value={loc} onChange={e=>setLoc(e.target.value)}><option>All</option><option>Online</option><option>Chennai</option><option>Coimbatore</option><option>Madurai</option><option>Trichy</option><option>Salem</option><option>Tamil Nadu</option><option>India</option></select><button onClick={load}>↻ Refresh</button></div>{loading?<div className="empty">Loading current opportunities…</div>:<div className="cards">{list.map((o,i)=><Card key={o.id||o.source_id||i} o={o} p={p} fb={fb} setFb={setFb}/>)}</div>}</section>
 <section id="explore"><div className="heading"><small>✦ EXPLORE</small><h2>Nearby, India-wide, <em>or online.</em></h2></div><div className="explore"><button onClick={()=>{setLoc("Tamil Nadu");setView("explore");document.getElementById("feed").scrollIntoView()}}>📍<b>Tamil Nadu</b><span>Opportunities near you</span></button><button onClick={()=>{setLoc("Online");setView("explore");document.getElementById("feed").scrollIntoView()}}>💻<b>Online</b><span>Remote opportunities</span></button><button onClick={()=>{setLoc("India");setView("explore");document.getElementById("feed").scrollIntoView()}}>🇮🇳<b>Across India</b><span>Explore beyond your city</span></button></div></section>
 <section className="assistant" id="assistant"><div><small>✦ ANEBESTRA AI</small><h2>Your AI assistant for <em>student life.</em></h2><p>Ask about opportunities, careers, skills, projects, resumes or your next step.</p></div><div className="chat"><header>✦ <b>ANEBESTRA</b><small>AI Student Assistant</small></header><main>{chat.map((x,i)=><p key={i} className={x.r}>{x.t}</p>)}{sending&&<p className="a">ANEBESTRA is thinking…</p>}</main><footer><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask ANEBESTRA something…"/><button onClick={send}>→</button></footer></div></section>
 <footer className="sitefoot"><img src={AENOVALogo}/><span>DISCOVER · LEARN · GROW</span><small>AENOVA — AI-powered opportunity discovery for students.</small></footer>
 {modal&&<div className="modalbg"><div className="modal"><header><div><small>✦ AENOVA ONBOARDING</small><h2>Let’s build your profile.</h2><p>Small steps. Better opportunities.</p></div><button onClick={()=>setModal(false)}>×</button></header><div className="steps">{["About","Education","Interests","Location","Alerts"].map((x,i)=><span className={i===step?"active":i<step?"done":""}>{i<step?"✓":i+1}<small>{x}</small></span>)}</div><div>{stepContent[step]}</div><div className="modalactions">{step>0&&<button onClick={()=>setStep(step-1)}>← Back</button>}{step<4?<button className="primary" onClick={()=>setStep(step+1)}>Next →</button>:<button className="primary" onClick={save}>{saving?"Saving…":"Finish Profile →"}</button>}</div>{msg&&<p className="msg">{msg}</p>}</div></div>}</div>
}
